version: "3"

volumes:
  bundle:

services:
  app:
    build:
      context: .
    command: bundle exec rake
    volumes:
      - .:/usr/src/app
      - "bundle:/bundle"
    environment:
      BUNDLE_PATH: /bundle